export const appRoutesNames = {
    HOME: 'home',
    TYPESCRIPT: 'typescript',
    DATA_BINDING: 'data-binding',
    EVENT_BINDING: 'event-binding',
    BUILT_IN_DIRECTIVES: 'built-in-directives',
    PIPES: 'pipes',
    TEMPLATE_DRIVEN_FORMS: 'template-driven-forms',
    MODEL_DRIVEN_FORMS: 'model-driven-forms',
    COMPONENT_COMMUNICATION: 'component-interaction',
    NOTIFICATIONS: 'notifications',
    CRUD: 'crud',
    ADD_USER: 'add-user',
    LIST_USER: 'list-user',
    EDIT_USER: 'edit-user',
};
